### ISSUE TITLE
Incorrect Beta Calculation in CAPM Analysis Script

### ISSUE THREAD

**Issue by k10nite** [HansFredrick/9365-4_R_Artifacts#3]
The CAPM analysis script incorrectly calculates beta due to a missing data normalization step. Without checking for missing values in the returns_data dataset, the regression model (lm) may include NA values, leading to inaccurate results.

**Comment by k10nite** [comment]
![Screenshot 2024-12-05 210727](https://github.com/user-attachments/assets/fedafd98-2116-4f9d-a889-9c38b1a0db44)

**Comment by HansFredrick** [comment]
this issue in now resolved
